package com.example.zhongyu.breakpointresume.Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "FILE_INFO".
 */
public class FileInfo {

    private Long id;
    /** Not-null value. */
    private String title;
    private double schedule;
    /** Not-null value. */
    private String fileurl;

    public FileInfo() {
    }

    public FileInfo(Long id) {
        this.id = id;
    }

    public FileInfo(Long id, String title, double schedule, String fileurl) {
        this.id = id;
        this.title = title;
        this.schedule = schedule;
        this.fileurl = fileurl;
    }

    public Long getId() {
        return id;
    }

    public FileInfo setId(Long id) {
        this.id = id;
        return this;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public FileInfo setTitle(String title) {
        this.title = title;
        return this;
    }

    public double getSchedule() {
        return schedule;
    }

    public FileInfo setSchedule(double schedule) {
        this.schedule = schedule;
        return this;
    }

    /** Not-null value. */
    public String getFileurl() {
        return fileurl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public FileInfo setFileurl(String fileurl) {
        this.fileurl = fileurl;
        return this;
    }

}
